import type { Metadata } from 'next'
import { Providers } from '../providers'
import { Sidebar } from '@/components/organisms/Sidebar'
import { Box, Flex } from '@chakra-ui/react'


export const metadata: Metadata = {
  title: 'X',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {

  return (
    <Providers>
      <Flex >
        <Sidebar />
        <Box as='main' flexGrow='3'>
          {children}
        </Box>
      </Flex>
    </Providers>

  )
}
