import type { Metadata } from 'next'
import { Providers } from '../providers'
import { Sidebar } from '@/components/organisms/Sidebar'
import { Box, Flex } from '@chakra-ui/react'


export const metadata: Metadata = {
  title: 'X',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {

  return (
    <Providers>
      <Flex minH='100vh'>
        <Sidebar />
        <Box as='main' flexGrow='1'>
          <Box w='990px'>
            <Flex justifyContent='space-between' w='100%'>
              {children}
            </Flex>
          </Box>
        </Box>
      </Flex>
    </Providers>

  )
}
