
import type { Metadata } from 'next'
import { Providers } from '../providers'
import { Sidebar } from '@/components/template/Sidebar'
import { Flex } from '@chakra-ui/react'
import { Main } from '@/components/template/Main'


export const metadata: Metadata = {
  title: 'X',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {

  return (
    <Providers>
      <Flex minH='100vh'>
        <Sidebar />
        <Main>
          {children}
        </Main>
      </Flex>
    </Providers>

  )
}
