import type { Metadata } from 'next'
import { Box } from '@chakra-ui/react';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {

  return (
    <Box as="html" lang="ja">
      <Box as="body" bg="black" color="white">
        {children}
      </Box>
    </Box>
  )
}
