import { ChakraProvider } from '@chakra-ui/react'
import type { Metadata } from 'next'
import "./globals.css";



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {

  return (
      <html lang="ja">
        <body className={"bg-black text-white"}>
          <ChakraProvider>
            {children}
          </ChakraProvider>
        </body>
      </html>
  )
}
