import { Box, Flex } from '@chakra-ui/react'
import type { Metadata } from 'next'
import { Providers } from '../providers'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <Providers>
      <Flex
        minH='100vh'
        alignItems='center'
        justifyContent='center'
        direction='column'
      >
        {children}
      </Flex>
    </Providers>
  )
}
